name: build process

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - uses: actions/cache@v3
        with:
          path: ./coverage.xml  # Note that this path is not influenced by working-directory set in defaults, for example
          key: coverage